# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpLOLvbK3vD29J2GmF8Ix_Eki_oYnanN
"""

import torch
from torch import nn
from torch.utils.data import dataloader
import torchvision
from torchvision import datasets, transforms

import matplotlib.pyplot
import os
import shutil

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pkdarabi/bone-break-classification-image-dataset")

print("Path to dataset files:", path)

import os
import shutil

original_root = "/kaggle/input/bone-break-classification-image-dataset/Bone Break Classification/Bone Break Classification"
new_root = "BoneBreakFixed"

for class_name in os.listdir(original_root):
    class_path = os.path.join(original_root, class_name)

    if not os.path.isdir(class_path):
        continue

    for split in ["Train", "Test"]:
        split_path = os.path.join(class_path, split)

        if not os.path.exists(split_path):
            continue

        new_split_path = os.path.join(new_root, split, class_name)
        os.makedirs(new_split_path, exist_ok=True)

        for img in os.listdir(split_path):
            src = os.path.join(split_path, img)
            dst = os.path.join(new_split_path, img)
            shutil.copy(src, dst)

print("Dataset Restructured Successfully!")

from pathlib import Path
image_path = Path("BoneBreakFixed")

train_dir = image_path/"Train"
test_dir = image_path/"Test"

from re import I
import random
from PIL import Image

random.seed(42)

image_path_list = list(image_path.glob("*/*/*.jpg"))
random_image_path = random.choice(image_path_list)
image_class = random_image_path.parent.stem
image = Image.open(random_image_path)
print(image_class)
image

train_dir

data_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.TrivialAugmentWide(num_magnitude_bins=20), # Keep TrivialAugmentWide for broader augmentation
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

test_augm = datasets.ImageFolder(train_dir, transform=data_transform)
test_augm = datasets.ImageFolder(test_dir, transform=test_transform)

len(test_augm.classes),
img, label = test_augm[0][0], test_augm[0][1]
img.shape

torch.manual_seed(42)
from torch.utils.data import DataLoader
train_dataloader = DataLoader(test_augm, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_augm, batch_size=32, shuffle=False)

train_dataloader

"""# All the data preprocessing is done now we are ready to develop our model
 we will build tnyvgg model architecture for classification
"""

class TinyVGG(nn.Module):
  def __init__(self, input_shape:int, hidden_units:int, output_shape:int):
    super().__init__()
    self.conv_block_1 = nn.Sequential(
        nn.Conv2d(input_shape, hidden_units, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.Conv2d(hidden_units, hidden_units, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2, stride=2)
    )
    self.conv_block_2 = nn.Sequential(
        nn.Conv2d(hidden_units, hidden_units, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.Conv2d(hidden_units, hidden_units, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2)
    )

    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(hidden_units*56*56, output_shape)
    )

  def forward(self, X:torch.Tensor):
    X = self.conv_block_1(X)
    X = self.conv_block_2(X)
    X = self.classifier(X)

    return X

len(train_data.classes), len(test_augm.classes)

torch.manual_seed(42)
M1 = TinyVGG(input_shape=3, hidden_units=10, output_shape=len(test_augm.classes))
M1

"""# the for loop in down works as follow

Great question — let’s untangle both parts: **how `len(test_pred_logits)` behaves** and **how the `for` loop works**.

---

### 1. What is `len(test_pred_logits)`?
- `test_pred_logits` is the output of your model for a batch of inputs `X`.
- Its shape is usually **[batch_size, num_classes]**.
  - `batch_size` = number of samples in that batch.
  - `num_classes` = number of possible labels (e.g., 10 for MNIST digits).

👉 So `len(test_pred_logits)` gives you the **batch size** (the number of rows).  
It does **not** change within a single batch — it’s fixed for that batch. But across batches, it can vary if your dataset size isn’t divisible by the batch size (the last batch might be smaller).

---

#### Example
Suppose:
- You have 4 samples in a batch.
- Your model predicts logits for 3 classes.

Then:
```python
test_pred_logits.shape = [4, 3]
```

Example tensor:
```python
tensor([[2.1, 0.5, -1.2],
        [0.1, 3.2, 1.5],
        [1.0, 0.3, 2.8],
        [4.2, 0.9, -0.7]])
```

- Each row = logits for one sample.
- `len(test_pred_logits)` = 4 (the batch size).
- `argmax(dim=1)` → `[0, 1, 2, 0]` (predicted class indices).

---

### 2. How the `for` loop works
```python
for batch, (X, y) in enumerate(dataloader):
```
- `dataloader` yields **batches** of `(X, y)` pairs.
- `X`: batch of inputs (e.g., images).
- `y`: batch of true labels.
- `batch`: just the batch index (0, 1, 2, …).

If your dataset has 100 samples and batch size = 20:
- Loop runs 5 times.
- Each time, `X` has shape `[20, ...]` (except maybe the last one).
- `y` has shape `[20]`.

---

#### Mini Example
Dataset = 10 samples, batch size = 4.

- **Batch 0** → `X.shape = [4, ...]`, `y.shape = [4]`
- **Batch 1** → `X.shape = [4, ...]`, `y.shape = [4]`
- **Batch 2** → `X.shape = [2, ...]`, `y.shape = [2]` (last batch smaller)

So `len(test_pred_logits)` = 4, 4, then 2 across the loop.

---

✅ **Key takeaway**:  
- `len(test_pred_logits)` = number of samples in the current batch.  
- The `for` loop runs once per batch, so the length can vary between iterations (especially the last batch).  

---

Would you like me to rewrite your `test_step` so that accuracy is computed **over all samples in the dataset** (instead of averaging batch accuracies)? That way, you’ll avoid small biases when batch sizes differ.

"""

def train_step(model: nn.Module,
               dataloader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer):
  model.train()

  train_loss, train_acc = 0, 0

  for batch, (X, y) in enumerate(dataloader):
    # Consider them as a list
    y_pred = model(X)

    loss = loss_fn(y_pred, y)
    train_loss += loss.item()

    optimizer.zero_grad()

    loss.backward()
    optimizer.step()
    y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
    train_acc += (y_pred_class == y).sum().item()/len(y_pred)

  train_loss = train_loss/len(dataloader)
  train_acc = train_acc/len(dataloader)

  return train_loss, train_acc

def test_step(model: nn.Module,
              dataloader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module):
  model.eval()

  test_loss, test_acc = 0, 0

  with torch.inference_mode():
    for batch, (X, y) in enumerate(dataloader):
      test_pred_logits = model(X)
      loss = loss_fn(test_pred_logits, y)
      test_loss += loss.item()
      test_pred_labels = test_pred_logits.argmax(dim=1)
      test_acc += ((test_pred_labels==y).sum().item()/len(test_pred_labels))

  test_loss = test_loss/len(dataloader)
  test_acc = test_acc/len(dataloader)
  return test_loss, test_acc

"""creating train function for combining bot the train and test step"""

from tqdm.auto import tqdm

def train(model: nn.Module,
          test_dataloader: torch.utils.data.DataLoader,
          train_dataloader: torch.utils.data.DataLoader,
          optimizer: torch.optim.Optimizer,
          epochs: int,
          loss_fn: nn.Module = nn.CrossEntropyLoss()):

  results = {"train_loss":[],
             "train_acc":[],
             "test_loss":[],
             "test_acc":[]}

  for epoch in tqdm(range(epochs)):
    train_loss, train_acc = train_step(model=model,
                                       dataloader=train_dataloader,
                                       loss_fn=loss_fn,
                                       optimizer=optimizer
                                       )
    test_loss, test_acc = test_step(model=model,
                                    dataloader=test_dataloader,
                                    loss_fn=loss_fn)

    print(f"epoch:{epoch+1} |"
          f"train_loss: {train_loss}"
          f"train_acc: {train_acc}"
          f"test_loss: {test_loss}"
          f"test_acc: {test_acc}")

    results["train_loss"].append(train_loss)
    results["train_acc"].append(train_acc)
    results["test_loss"].append(test_loss)
    results["test_acc"].append(test_acc)

  return results

torch.manual_seed(42)

num_epochs = 5
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(M1.parameters(), lr=0.001)

from timeit import default_timer as timer
start_time = timer()
M1_results = train(model=M1,
                   test_dataloader=test_dataloader,
                   train_dataloader=train_dataloader,
                   loss_fn=loss_fn,
                   epochs=5,
                   optimizer=optimizer)
end_time = timer()
print(f"Total training time:{start_time-end_time:.3f} seconds")

31360





